### ISSUE TITLE
tag programming workflow

### ISSUE THREAD

**Issue by bahnfrei** [marc136/tonuino-nfc-tools#2]
while attaching new tags to the smartphone, the following dialog comes up, which is ok:

![1-new](https://user-images.githubusercontent.com/10193241/58088683-7d261e00-7bc3-11e9-82f0-155b73c80c37.png)

if you then select "Tag beschreiben" from the main screen, adjust values according to your needs and push the below button "Tag beschreiben", the following error dialog comes up: 

![2-error](https://user-images.githubusercontent.com/10193241/58088855-d42bf300-7bc3-11e9-8b87-f9a1915a1f3e.png)

it only works, if you first select "Tag beschreiben" from the main screen, secondly attach the new tag to the device, adjust settings and select the "new" button" "Daten auf Tag \<tagid\> schreiben":

![3-ok](https://user-images.githubusercontent.com/10193241/58088862-d8581080-7bc3-11e9-842f-b2e3b4a3873e.png)

**Comment by bahnfrei** [comment]
i figured out a similar issue while adjusting an already configured tag: it's working as long as the tagid is available/shown in the "Bearbeiten" menu, but sometimes, the tagid is missing, so the modification(s) wont be saved.

**Comment by marc136** [comment]
Hello @bahnfrei, thanks for the feedback.

A problem with using NFC is that the tags don't have an open connection but are usually one-off read/write operations. So the connection to a tag might be lost at any time (I also noticed that when I put my phone on a tag, it will re-find that tag quite often..).

I will try to fix this in v0.3.1
> if you then select "Tag beschreiben" from the main screen, adjust values according to your needs and push the below button "Tag beschreiben", the [no tag found] error dialog comes up

I'm trying to fix this by disabling the "write button" if no tag is known, see [fc6b14](ccae2b950673660fc408ed269f6eceb079).

> it's working as long as the tagid is available/shown in the "Bearbeiten" menu, but sometimes, the tagid is missing, so the modification(s) wont be saved.

This might be partially fixed with the first change, but I will try to poll for the NFC tag and disable the button if the tag is out of range (with a small delay).

**Comment by bahnfrei** [comment]
Seems to be ok in 0.3.1#6, thx!
